---
# Install the dotfiles symlinks and their parent directories one by one
- name: Ensure directory is present
  file:
    path: "{{ item.dest | dirname }}"
    state: directory

- name: Ensure files are linked
  file:
    dest: "{{ item.dest }}"
    src: "{{ dotfiles_directory }}/{{ item.src }}"
    state: link
    mode: "{{ item.mode | default(0644) }}"
    force: yes
  register: dotfiles_register
  notify:
    - "Run post commands"

- name: Add post_command to list of post items
  set_fact:
    dotfiles_post_items: "{{ dotfiles_post_items }} + [ '{{ item.post_command }}' ]"
  when: dotfiles_register.changed and item.post_command is defined
