---
# handlers file for ansible-dotfiles
- name: Run post commands
  shell: "{{ansible_user_shell}} -i -l -c '{{ item }}'"
  args:
    chdir: "{{ dotfiles_directory }}"
  with_items: "{{ dotfiles_post_items }}"
  tags:
    - skip_ansible_lint
