---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: ubuntu18
    image: ubuntu:18.04
  - name: ubuntu20
    image: ubuntu:20.04
provisioner:
  name: ansible
scenario:
  name: default
  test_sequence:
    - destroy
    - syntax
    - lint
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
